meta_product_name: "Sportner"
meta_title: "Sportner - Trouves ton parnetaire de sport !"
meta_description: "Sportner te mets en relation avec les sportifs autour de chez toi !"
meta_image: "logosportnermeta.png"
